### ISSUE TITLE
Add a README

### ISSUE THREAD

**Issue by zmt** [spiffe/spire-plugin-sdk#16]
As a member of the SPIFFE community, I have a pretty good idea what this repo is about just by the name. As a consumer, I want more details, including, but not limited to:
* intended use
* supported use cases
* unsupported use cases
* examples
* troubleshooting guide (e.g. grpc version issues, etc.)

**Comment by azdagron** [comment]
This is, at least partially, covered by #15. I totally forgot it hadn't been merged yet. Thanks for the indirect reminder :)
