### ISSUE TITLE
Setup GitHub Actions workflows for this repository

### ISSUE THREAD

**Issue by evan2645** [spiffe/spire-plugin-sdk#24]
In https://github.com/spiffe/spire-plugin-sdk/pull/23 @rturner3 fixed up the dirty check function in the Makefile, but noted in Slack that we don't have any worklows that enforce this

We should be able to ensure that, at a minimum, everything compiles and updated protos have been regenerated. To start, the workflow should be run for each PR, and each change to the main branch

**Comment by azdagron** [comment]
Fixed by #28
