### ISSUE TITLE
Incorrect attestation flow wording in server nodeattestor.proto comments  ?

### ISSUE THREAD

**Issue by udf2457** [spiffe/spire-plugin-sdk#44]
The comments at the top of `server/nodeattestor/v1/nodeattestor.proto` are perhaps misworded ?

`2. SPIRE Server sends a request containing the attestation payload received from the agent.`

Should this not be "_receives a request_" and remove "_received_" (so the end reads '_received from the agent_").

`4. The plugin returns the attestation results to SPIRE Server and closes the stream.`

Should this not be "_to Spire Agent_" ?

**Comment by azdagron** [comment]
The text here is explaining the attestation flow from the perspective of the _server-side plugin_.  In step 2, SPIRE Server sends the payload received from SPIRE agent down to the plugin over the Attest stream opened in step 1.

Similarly in step 4, the plugin does not return anything to SPIRE Agent. It returns it to the Server (who in turn returns it to SPIRE Agent).

With that perspective in mind, is the existing wording clear? If not, please open a PR with some suggested improvements!

**Comment by azdagron** [comment]
I'll close this issue for now. Please let us know if you feel that more action is required. Thanks!
