### ISSUE TITLE
Clarification required about AgentAttributes in node attestation

### ISSUE THREAD

**Issue by udf2457** [spiffe/spire-plugin-sdk#45]
According to the comments in the code:

On the agent side (agent/nodeattestor/v1/nodeattestor.proto) we are told that spire agent awaits challenges from the server, and if no further challenges are received, can close the stream.

However, on the server side (server/nodeattestor/v1/nodeattestor.proto), we are told that `AgentAttributes` is "Required as the last response.".

It is therefore not clear how this fits in with the agent.  Becuase if the agent closes the stream when it receives no further challenges, the server will surely be unable to send `AgentAttributes` ?  

Or does this magically happen in the background somewhere ?

Whichever way, more clarification needed, please !

**Comment by azdagron** [comment]
There are 4 parties involved in a node attestation flow. The agent, the agent-side plugin, the server, and the server-side plugin.

The agent and server more or less act as a conduit between the agent-side and server-side plugins.

The server-side plugin verifies the attestation data and performs zero or more challenge responses (if any, it is solely up to the plugins). The end result of successful attestation is the agent attributes returned by the server-side plugin to the server. Those attributes _are never sent to the agent_ (and therefore, the agent-side plugin), but are rather recorded and used to inform the SPIFFE ID to use in the SVID minted for the agent.

**Comment by azdagron** [comment]
I'll close this issue for now. Please let us know if you feel that more action is required. Thanks!
