### ISSUE TITLE
Improvement on documentation for authoring plugins

### ISSUE THREAD

**Issue by guilhermocc** [spiffe/spire-plugin-sdk#46]
We don't have examples for authoring different kinds of plugins that are defined here. This issue proposes an improvement in the Authoring documentation section to have at least one actual example of plugin implementation for each plugin type (agent and server).  I'm willing to work on this :smile:

**Comment by guilhermocc** [comment]
We already have plugin templates. Maybe we should link them to the Authoring page

**Comment by azdagron** [comment]
I think linking the templates to the authoring page is a fine idea.
